version: "3.8"
services:
  backend-oneclickinsight:
    container_name: backend-oneclickinsight
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CELERY_RESULT_BACKEND: "${REDIS_URL}"
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//"
    networks:
      ailyze-nw:
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
      - /AILYZE/staticfiles
    env_file:
      - ./.env
    command: sh -c "gunicorn --bind 0.0.0.0:8000 AILYZE.asgi:application -w 2 -k uvicorn.workers.UvicornWorker --timeout 120 --access-logfile -  --error-logfile -"

