version: "3.8"
services:
  backend-chatbot:
    container_name: backend-chatbot
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CELERY_RESULT_BACKEND: "${REDIS_URL}"
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//"
    networks:
      ailyze-nw:
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    env_file:
      - ./.env
    command: sh -c "ls && gunicorn --bind 0.0.0.0:8000 --timeout 300 --access-logfile - --error-logfile - AILYZE.wsgi"
