version: "3.8"
services:
  celery-1:
    image: celery
    container_name: celery-1
    restart: always
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "${REDIS_URL}"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    command: celery  -A AILYZE worker -l info --autoscale=10,4 -Q themeandresearchquestion -n theme -Ofair
    depends_on:
      - redis
      - rabbitmq
      - backend-oneclickinsight
    env_file:
     - ./.env
    networks:
      ailyze-nw:

  celery-2:
    image: celery
    container_name: celery-2
    restart: always
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "${REDIS_URL}"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    command: celery -A AILYZE worker -l info --autoscale=10,4 -Q addfilequeue -n addfile -Ofair
    depends_on:
      - redis
      - rabbitmq
      - backend-oneclickinsight
    env_file:
     - ./.env
    networks:
      ailyze-nw:

  celery-3:
    image: celery
    container_name: celery-3
    restart: always
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "${REDIS_URL}"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    command: celery -A AILYZE worker -l info --autoscale=10,4 -Q compareviewpoint -n compare -Ofair
    depends_on:
      - redis
      - rabbitmq
      - backend-oneclickinsight
    env_file:
     - ./.env
    networks:
      ailyze-nw:
      
  celery-beat-worker:
    image: celery
    container_name: celery_beat
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "${REDIS_URL}"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    command: celery  -A AILYZE beat -l info
    env_file:
     - ./.env
    depends_on:
      - redis
      - rabbitmq
      - backend-oneclickinsight
    networks:
      ailyze-nw:

  celery-5:
    image: celery
    container_name: celery-5
    restart: always
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "${REDIS_URL}"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    command: celery -A AILYZE worker -l info --autoscale=10,4 -Q transcription -n transcription -Ofair
    depends_on:
      - redis
      - rabbitmq
      - backend-oneclickinsight
    env_file:
     - ./.env
    networks:
      ailyze-nw:


  celery-6:
    image: celery
    container_name: celery-celery
    restart: always
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "${REDIS_URL}"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    command: celery -A AILYZE worker -l info --autoscale=10,4 -Q celery -n celery -Ofair
    depends_on:
      - redis
      - rabbitmq
      - backend-oneclickinsight
    env_file:
     - ./.env
    networks:
      ailyze-nw:

  celery-7:
    image: celery
    container_name: celery-7
    restart: always
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "${REDIS_URL}"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    command: celery -A AILYZE worker -l info --autoscale=10,4 -Q imagetranscription -n imagetranscription -Ofair
    depends_on:
      - redis
      - rabbitmq
      - backend-oneclickinsight
    env_file:
     - ./.env
    networks:
      ailyze-nw:

  celery-8:
    image: celery
    container_name: celery-8
    restart: always
    build:
      context: ../Ailyze_openai_dajngo/AILYZE/
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "${REDIS_URL}"
    volumes:
      - ../Ailyze_openai_dajngo/AILYZE:/AILYZE
    command: celery -A AILYZE worker -l info --autoscale=10,4 -Q getdata -n getdata -Ofair
    depends_on:
      - redis
      - rabbitmq
      - backend-oneclickinsight
    env_file:
     - ./.env
    networks:
      ailyze-nw:

